cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('remove/', views.CartRemoveView.as_view(), name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name='coupons'

urlpatterns=[
    path('apply/', views.CouponApplyView.as_view(), name='apply'),
]

my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from shop.views import UserLoginView,ProductListView, UserLogoutView
from django.contrib.auth import views as auth_views

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('', ProductListView.as_view(), name='product_list'),
    path('login/',UserLoginView.as_view(), name='login'),
    path('logout/',UserLogoutView.as_view(), name='logout'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'),include('payment.urls',namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
   
)

if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name='orders'

urlpatterns=[
    path(_('create/'), views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/',views.admin_order_pdf, name='admin_order_pdf'),
    path('actionUrl/', views.sort_btn, name='actionUrl'),
]

cart/models.py
from django.contrib.auth.models import User
from django.db import models
from shop.models import Product


# Create your models here.
class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class CartItems(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.IntegerField()
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='cart_item')

    

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

# PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField( required = True,label=_('Quantity'))
    override = forms.BooleanField(required=False, initial=True, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http.response import JsonResponse
from django.views.decorators.http import require_POST
from shop.models import Product
from .models import Cart, CartItems
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from shop.recommender import Recommender
from django.contrib.auth.decorators import login_required
from shop.views import UserLoginView
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

# @login_required
# @require_POST
class CartAddView(LoginRequiredMixin,View):
    
    def post(self, request, product_id):

        # check if user has cart
        if not Cart.objects.filter(user=self.request.user).exists():
            cart= Cart.objects.create(user=self.request.user)
        else: 
            cart= Cart.objects.get(user=self.request.user)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            # check if the product is in cart
            if not CartItems.objects.filter(product_id=product_id).exists():
                cartitem= CartItems.objects.create(product_id=product_id, qty=request.POST.get('quantity'), cart=cart)
            else: 
                cartitem= CartItems.objects.get(product_id=product_id)
                cartitem.qty = cartitem.qty + request.POST.get('quantity')
                cartitem.save()

            cd = form.cleaned_data
        print("here")
        return redirect('cart:cart_detail')

class CartRemoveView(LoginRequiredMixin, View):    
    def post(self,request):
        product_id =  self.request.POST.get('del_id')
        # print('jhassvxdghsh')
        cart = Cart()
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        
        return JsonResponse(data={"status": 204})

    
class CartDetailView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
  
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'override': True})
        coupon_apply_form = CouponApplyForm()
        r = Recommender()
        cart_products = [item['product'] for item in cart]
        # recommended_products = r.suggest_products_for(cart_products, max_results=4)
        return render(request, 'cart/detail.html', {'cart': cart,
                                                    'coupon_apply_form': coupon_apply_form,
                                                    'recommended_products': {}})
        

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load i18n %}

{% load static %}

{% block title %}
 My shopping cart
{% endblock %}

{% block content %}

    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    {% trans 'Your cart' %}:
                    <a href="{% url 'cart:cart_detail' %}">
                        {% blocktrans with total=cart.get_total_price count items=total_items %}
                            {{ items }} item, Rs.{{ total }}
                        {% plural %}
                        <span id="total-item-cart">{{ items }}</span> items, Rs. <span id="total-price-cart">{{ total }}</span>
                        {% endblocktrans %}                        
                    </a>
                {% else %}
                    {%  trans 'Your cart is empty.' %}
                {% endif %}
            {% endwith %}
        </div>
    </div>

    <h1>My shopping cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Total Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url}}
                        {% else %}{% static 'img/no_image.png' %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td  id=" qty">
                    <!-- {{ item.update_quantity_form.quantity }} -->
                    <input type="button" name="subtract"  class= "subtract" id="subtract" value="-"></input>
                    <input type="button" name="add" class="add" id="add" value="+"></input>
                    <input type="text" name="qty"  class="qty" id="qty" value="{{item.quantity}}"></input>
                    
       
                </td>
                <td>
                    {% comment %} <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                        <input type="submit" class="remove" value="Remove">
                        {% csrf_token %}
                    </form> {% endcomment %}
                    <input type="submit" class="remove" value="remove" data-product-id= '{{product.id}}'> 
                </td>
                
                <td class="num price" id="price">{{ item.price }}
                  

                </td>
                <td class="num total" id="total">{{ item.total_price }}</td>
            </tr>
            {% endwith %}
            {% endfor %}




            {% if cart.coupon %}
                <tr class="subtotal" id="total">
                    <td id="total">Subtotal</td>
                    <td colspan="4"></td>
                    <td class="num" id="total">{{ cart.get_total_price|floatformat:2 }}</td>
                </tr>
                <tr>
                    <td>
                    "{{ cart.coupon.code }}" coupon 
           
                    ({{ cart.coupon.discount }}% off)
                    </td>
                <td colspan="4"></td>
                rs.<td class="num neg">
                    - {{ cart.get_discount|floatformat:2 }}
                </td>
                </tr>
            {% endif %}

                <tr class="final-total" id="total">
                    <td>Total</td>
                    <td colspan="4"></td>
                    <td class="final-num" id="final-num">
                    Rs.{{ cart.get_total_price_after_discount|floatformat:2 }}
                    </td>
                </tr>
        </tbody>
    </table>

    {% if recommended_products %}
        <div class="recommendations cart">
            <h3>{% trans "People who bought this also bought" %}</h3>
            {% for p in recommended_products %}
                <div class="item">
                    <a href="{{ p.get_absolute_url }}">
                        <img src="{% if p.image %}{{ p.image.url }}{% else %}
                        {% static 'img/no_image.png' %}{% endif %}">
                    </a>
                    <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <p>Apply a coupon:</p>
    <form action="{% url 'coupons:apply' %}" method="post">
        {{ coupon_apply_form }}
        <input type="submit" value="Apply">
        {% csrf_token %}
    </form>

        <p class="text-right">
            <a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
            <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
        </p>

    <script>
            $(function() {
                function calcuate_total(){
                    var total_sum = 0
                    $('.total').each(function(){
                        
                        total_sum += parseFloat($(this).text())
                    
                    })
                    $("#final-num").html("Rs."+total_sum)
                    $("#total-price-cart")[0].innerText = total_sum
                } 

                function calculateFinalItem(){
                    var total_item = 0
                    $.each($('.qty'),function(key, value){

                        total_item += parseInt($(this).val())                      
                      })
                      $('#total-item-cart')[0].innerText= total_item
                }

                    var price = parseFloat($('.price').text());

                    $('.subtract').on("click",function() {
                        tr =$(this).closest('tr');
                        price = parseFloat($(tr).find('.price').text())
                        qty = $(tr).find('.qty');
                       
                        var current = parseInt(qty.val());
                        if ( current > 0 ) {
                            qty.val(current-1) 
                            $(tr).find('.total').text(price*parseInt(qty.val()));
                            
                        } else {
                            $(tr).find('.total').text(0);
                        }
                        calcuate_total()
                        calculateFinalItem()
                    });
        
                $('.add').on("click",function() {
                    tr = $(this).closest('tr');
                    price = parseFloat($(tr).find('.price').text());
                    let qty = $(tr).find('.qty');
                    var current = parseInt(qty.val());
                    qty.val(current+1);
                    $(tr).find('.total').text(price*parseInt(qty.val()))

                    calcuate_total()
                    calculateFinalItem()

                });

    
           

       

          // removing item from cart
          $('.remove').click(function(){
               let del_id = $(this).attr('data-product-id'); //to get the product id of item to be removed

               let quantity_col = $(this).parent().siblings() //to get tha quantity div of the item to be removed          
               
               deleteitem(del_id, this);

               //updating price after deletion of product in cart
               let totalPrice=$('#final-num')[0].innerText //gets the final total price
               let totalAmount= quantity_col[4].innerText //gets the unit price of the product that is to be removed
               totalPrice=totalPrice.replace("Rs.","") //to remove "rs." from amount variable
               const finalTotalPrice = parseInt(totalPrice)-parseInt(totalAmount) //subtracting total price of removed item from the final total price
               $('#final-num')[0].innerText = `Rs.${finalTotalPrice}`
               $("#total-price-cart")[0].innerText = finalTotalPrice
               

                // calculate quantity after product deletion from cart
               let quanCol= quantity_col[2]
               console.log(quanCol)
               let quantity=$("#total-item-cart")[0].innerText
               $(quanCol).children().each(function(idx, val){
                if(val.getAttribute("id")==="qty"){
                    quantity = parseInt(quantity)- parseInt($(val).val())
                }
            })
            $("#total-item-cart")[0].innerText=quantity
          })
        });  
        
                
          function deleteitem(del_id, _this){
                $.ajax({
                    type:'POST',
                    url : '{% url "cart:cart_remove" %}',
                    data : {
                        'del_id': del_id,
                        'csrfmiddlewaretoken': '{{csrf_token}}'
                    },
                    success:function(response){
                        if(response.status === 204){
                            
                            $(_this).parent().parent().remove(); // Dom maniplation
                        }
                    }
                })
          }  
         
         
        
    </script>
        
  
{% endblock %}