cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('remove/', views.CartRemoveView.as_view(), name='cart_remove'),
]

my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from shop.views import UserLoginView,ProductListView, UserLogoutView
from django.contrib.auth import views as auth_views

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('', ProductListView.as_view(), name='product_list'),
    path('login/',UserLoginView.as_view(), name='login'),
    path('logout/',UserLogoutView.as_view(), name='logout'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'),include('payment.urls',namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
   
)

if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
# from django.views import View

app_name= 'shop'

urlpatterns=[
    # path('', views.product_list, name='product_list'),
    # path('search/', views.post_search, name='post_search'),
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<slug:category_slug>/', views.ProductListView.as_view(), name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from parler.models import TranslatableModel, TranslatedFields

# Create your models here.

class Category(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(max_length=200, db_index=True),
        slug = models.SlugField(max_length=200, db_index= True, unique= True)
    )

    class Meta:
        # ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(max_length=200, db_index=True),
        slug = models.SlugField(max_length=200, db_index=True),
        description = models.TextField(blank=True)
    )
    
    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # class Meta:
    #     ordering = ('name',)
    #     index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)\

class SearchForm(forms.Form):
    query = forms.CharField()


    

shop/views.py
from cart.forms import CartAddProductForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import SearchVector
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.utils.translation import gettext_lazy as _
from django.views import View

from .forms import LoginForm, SearchForm
from .models import Category, Product
from .recommender import Recommender

# Create your views here.


class UserLoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
        #     # login(request,user) 
            return redirect ('shop:product_list')
        
        form = LoginForm()
        return render(request, 'shop/account/login.html', {'form': form})
    
    def post(self,request):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
        if user is not None:          
                
            if user.is_active:
                login(request, user)
                return redirect ('shop:product_list')
                
            else:
                return HttpResponse('Disabled account')
        else:
            return HttpResponse('Invalid login')


class UserLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('login')

class ProductListView(View):
    def get(self,request, category_slug=None):
        category =  None
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)

        paginator = Paginator(products,3)
        page_number = request.GET.get('page')
        product_data_final = paginator.get_page(page_number)

        
        

        if category_slug:   
            language =  request.LANGUAGE_CODE
            category = get_object_or_404(Category, 
                                        translations__language_code = language,
                                        translations__slug=category_slug)
            product_data_final = product_data_final.filter(category=category)

       

        search_param = request.GET.get('q',None)
        if search_param:
            product_data_final = products.filter(translations__name__icontains=search_param)
        
        return render(request, 'shop/product/list.html', {'category': category,
                                                            'categories': categories,
                                                            # 'products': products,
                                                            'product_data': product_data_final})

class ProductDetailView(View):
    def get(self, request, id, slug):
        language = request.LANGUAGE_CODE
     
        # products = Product.objects.filter(id=id,
        #                             translations__language_code = language,
        #                             translations__slug=slug,
        #                             available=True)

        product = []
        try:
            product= get_object_or_404(Product, 
                                        id=id,
                                        translations__language_code = language,
                                        translations__slug=slug,
                                        available=True)
        except:
            print("No object found...")
        
        cart_product_form = CartAddProductForm()

        r= Recommender()
        recommended_products= r.suggest_products_for([product], 4)
        return render (request, 'shop/product/detail.html', {'product': product,
                                                            'cart_product_form': cart_product_form,
                                                            'recommended_products': recommended_products})

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}
 {{ product.name }}
{% endblock %}

{% block content %}
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    {% trans 'Your cart' %}:
                    <a href="{% url 'cart:cart_detail' %}">
                        {% blocktrans with total=cart.get_total_price count items=total_items %}
                            {{ items }} item, Rs. {{ total }}
                        {% plural %}
                            {{ items }} items, Rs. {{ total }}
                        {% endblocktrans %}                        
                    </a>
                {% else %}
                    {%  trans 'Your cart is empty.' %}
                {% endif %}
            {% endwith %}
        </div>
    </div>

    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}
        {% else %}{% static 'img/no_image.png' %}{% endif %}">
        <h1>{% trans product.name %}
            <!-- {% blocktranslate %} -->
            <!-- {{product.name}} -->
            <!-- {% endblocktranslate %} -->
        </h1>
        <h2>
            <a href="{{ product.category.get_absolute_url }}">
                {{ product.category }}
            </a>
        </h2>
        <p class="price">Rs. {{ product.price }}</p>

        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <!-- <a href="#" class="button">Add to cart</a> -->
            <input type="submit" value="{% trans 'Add to cart' %}">
        </form>
        {{ product.description|linebreaks }}

        {% if recommended_products %}
            <div class="recommendations">
                <h3>{% trans "People who bought this also bought" %}</h3>
                {% for p in recommended_products %}
                    <div class="item">
                        <a href="{{p.get_absolute_url}}">
                            <img src="{% if p.image %}{{ p.image.url }} 
                            {% else %}{% static 'img/no_image.png' %}{% endif %}">
                            {% trans p.name %}
                        </a>
                        
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load i18n %}

{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    {% trans 'Your cart' %}:
                    <a href="{% url 'cart:cart_detail' %}">
                        {% blocktrans with total=cart.get_total_price count items=total_items %}
                            {{ items }} item, Rs. {{ total }}
                        {% plural %}
                            {{ items }} items, Rs. {{ total }}
                        {% endblocktrans %}                        
                    </a>
                {% else %}
                    {%  trans 'Your cart is empty.' %}
                {% endif %}
            {% endwith %}
        </div>
    </div>

    <div id="sidebar">

        {% comment %} <form action="{% url 'shop:product_list' %}" method="get">
            <input name="q" type="text" placeholder="filter by...">
            <button type='submit'>Filter</button>
        </form> {% endcomment %}

        <form action="{% url 'shop:product_list' %}" method="get">
            <input name="q" type="text" placeholder="Search...">
            <button type='submit'>Search</button>
        </form> 

        <br>
    
        

        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url 'shop:product_list' %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
        <br>

        <h3>Price</h3>
        <li>
            <input type='range'  id="rangeInput" min='0' max='1000' oninput='MaxPrice.value=this.value'>
        </li>
        <li>
            Max:<input type='number' onkeyup='rangeInput.value=this.value' id='MaxPrice' min='0' max='1000'>
        </li>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in product_data %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img  id ='abcimage' src="{% if product.image %}{{ product.image.url }}
                    {% else %}{% static 'img/no_image.png' %}{% endif %}">
                </a>
                <br>
                <a href="{{product.get_absolute_url}}">{{ product.name }}</a>
                <br>
                Rs.{{ product.price }}
                {% comment %} <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input type="submit" value="{% trans 'Buy Now' %}">
                </form> {% endcomment %}
            </div>
        {% endfor %}
    </div>

    <nav aria-label="...">
        <ul class="pagination">
          {%  if product_data.has_previous %}
          <li class="page-item ">
            <a class="page-link" href="/shop/?page=1" tabindex="-1">First</a>
          </li>
          <li class="page-item ">
            <a class="page-link" href="/shop/?page={{ product_data.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% endif %}              
      
          {% if product_data.has_next %}
          <li class="page-item">
            <a class="page-link" href="/shop/?page={{ product_data.next_page_number }}">Next</a>
          </li>
          {% endif %}
        </ul>
      </nav>
{% endblock %}